# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'TraderGUI.ui'
#
# Created by: PyQt4 UI code generator 4.11.4
#
# WARNING! All changes made in this file will be lost!

from PyQt4 import QtCore, QtGui

try:
    _fromUtf8 = QtCore.QString.fromUtf8
except AttributeError:
    def _fromUtf8(s):
        return s

try:
    _encoding = QtGui.QApplication.UnicodeUTF8
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig, _encoding)
except AttributeError:
    def _translate(context, text, disambig):
        return QtGui.QApplication.translate(context, text, disambig)

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName(_fromUtf8("MainWindow"))
        MainWindow.resize(2558, 1756)
        MainWindow.setMinimumSize(QtCore.QSize(2558, 1756))
        MainWindow.setMaximumSize(QtCore.QSize(16777215, 16777215))
        MainWindow.setStyleSheet(_fromUtf8("background-color: rgb(0, 0, 0);"))
        self.centralwidget = QtGui.QWidget(MainWindow)
        self.centralwidget.setObjectName(_fromUtf8("centralwidget"))
        self.gridLayout = QtGui.QGridLayout(self.centralwidget)
        self.gridLayout.setObjectName(_fromUtf8("gridLayout"))
        self.horizontalLayout = QtGui.QHBoxLayout()
        self.horizontalLayout.setObjectName(_fromUtf8("horizontalLayout"))
        self.frame_2 = QtGui.QFrame(self.centralwidget)
        self.frame_2.setMinimumSize(QtCore.QSize(0, 0))
        self.frame_2.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);\n"
""))
        self.frame_2.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_2.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_2.setObjectName(_fromUtf8("frame_2"))
        self.gridLayout_2 = QtGui.QGridLayout(self.frame_2)
        self.gridLayout_2.setObjectName(_fromUtf8("gridLayout_2"))
        self.horizontalLayout_13 = QtGui.QHBoxLayout()
        self.horizontalLayout_13.setObjectName(_fromUtf8("horizontalLayout_13"))
        self.label = QtGui.QLabel(self.frame_2)
        font = QtGui.QFont()
        font.setPointSize(25)
        font.setBold(False)
        font.setWeight(50)
        self.label.setFont(font)
        self.label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label.setObjectName(_fromUtf8("label"))
        self.horizontalLayout_13.addWidget(self.label)
        spacerItem = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem)
        self.datetime_display = QtGui.QLabel(self.frame_2)
        self.datetime_display.setMinimumSize(QtCore.QSize(310, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.datetime_display.setFont(font)
        self.datetime_display.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.datetime_display.setText(_fromUtf8(""))
        self.datetime_display.setObjectName(_fromUtf8("datetime_display"))
        self.horizontalLayout_13.addWidget(self.datetime_display)
        self.gridLayout_2.addLayout(self.horizontalLayout_13, 0, 0, 1, 2)
        spacerItem1 = QtGui.QSpacerItem(58, 22, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem1, 1, 0, 1, 1)
        self.horizontalLayout_10 = QtGui.QHBoxLayout()
        self.horizontalLayout_10.setObjectName(_fromUtf8("horizontalLayout_10"))
        self.frame_3 = QtGui.QFrame(self.frame_2)
        self.frame_3.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame_3.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_3.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_3.setObjectName(_fromUtf8("frame_3"))
        self.formLayout_4 = QtGui.QFormLayout(self.frame_3)
        self.formLayout_4.setObjectName(_fromUtf8("formLayout_4"))
        self.label_8 = QtGui.QLabel(self.frame_3)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_8.setFont(font)
        self.label_8.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);\n"
"color: rgb(255, 255, 255);"))
        self.label_8.setObjectName(_fromUtf8("label_8"))
        self.formLayout_4.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_8)
        self.line_5 = QtGui.QFrame(self.frame_3)
        self.line_5.setMinimumSize(QtCore.QSize(311, 16))
        self.line_5.setLineWidth(3)
        self.line_5.setFrameShape(QtGui.QFrame.HLine)
        self.line_5.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_5.setObjectName(_fromUtf8("line_5"))
        self.formLayout_4.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line_5)
        self.horizontalLayout_5 = QtGui.QHBoxLayout()
        self.horizontalLayout_5.setObjectName(_fromUtf8("horizontalLayout_5"))
        self.horizontalLayout_4 = QtGui.QHBoxLayout()
        self.horizontalLayout_4.setObjectName(_fromUtf8("horizontalLayout_4"))
        spacerItem2 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_4.addItem(spacerItem2)
        self.year_lcd = QtGui.QLCDNumber(self.frame_3)
        self.year_lcd.setMinimumSize(QtCore.QSize(0, 0))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.year_lcd.setFont(font)
        self.year_lcd.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);\n"
"border: 0px solid black"))
        self.year_lcd.setObjectName(_fromUtf8("year_lcd"))
        self.horizontalLayout_4.addWidget(self.year_lcd)
        self.horizontalLayout_5.addLayout(self.horizontalLayout_4)
        spacerItem3 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem3)
        self.formLayout_4.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_5)
        self.horizontalLayout_10.addWidget(self.frame_3)
        spacerItem4 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem4)
        self.frame_4 = QtGui.QFrame(self.frame_2)
        self.frame_4.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame_4.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_4.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_4.setObjectName(_fromUtf8("frame_4"))
        self.formLayout_5 = QtGui.QFormLayout(self.frame_4)
        self.formLayout_5.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_5.setObjectName(_fromUtf8("formLayout_5"))
        self.line_6 = QtGui.QFrame(self.frame_4)
        self.line_6.setMinimumSize(QtCore.QSize(337, 16))
        self.line_6.setLineWidth(3)
        self.line_6.setFrameShape(QtGui.QFrame.HLine)
        self.line_6.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_6.setObjectName(_fromUtf8("line_6"))
        self.formLayout_5.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line_6)
        self.horizontalLayout_6 = QtGui.QHBoxLayout()
        self.horizontalLayout_6.setObjectName(_fromUtf8("horizontalLayout_6"))
        self.horizontalLayout_7 = QtGui.QHBoxLayout()
        self.horizontalLayout_7.setObjectName(_fromUtf8("horizontalLayout_7"))
        spacerItem5 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_7.addItem(spacerItem5)
        self.month_lcd = QtGui.QLCDNumber(self.frame_4)
        self.month_lcd.setMinimumSize(QtCore.QSize(180, 81))
        self.month_lcd.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);\n"
"border: 0px solid black\n"
""))
        self.month_lcd.setObjectName(_fromUtf8("month_lcd"))
        self.horizontalLayout_7.addWidget(self.month_lcd)
        self.horizontalLayout_6.addLayout(self.horizontalLayout_7)
        spacerItem6 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_6.addItem(spacerItem6)
        self.formLayout_5.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_6)
        self.label_9 = QtGui.QLabel(self.frame_4)
        self.label_9.setMinimumSize(QtCore.QSize(322, 0))
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_9.setFont(font)
        self.label_9.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);\n"
"color: rgb(255, 255, 255);"))
        self.label_9.setObjectName(_fromUtf8("label_9"))
        self.formLayout_5.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_9)
        self.horizontalLayout_10.addWidget(self.frame_4)
        spacerItem7 = QtGui.QSpacerItem(88, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_10.addItem(spacerItem7)
        self.frame_5 = QtGui.QFrame(self.frame_2)
        self.frame_5.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame_5.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_5.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_5.setObjectName(_fromUtf8("frame_5"))
        self.formLayout_6 = QtGui.QFormLayout(self.frame_5)
        self.formLayout_6.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_6.setObjectName(_fromUtf8("formLayout_6"))
        self.line_7 = QtGui.QFrame(self.frame_5)
        self.line_7.setMinimumSize(QtCore.QSize(311, 16))
        self.line_7.setLineWidth(3)
        self.line_7.setFrameShape(QtGui.QFrame.HLine)
        self.line_7.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_7.setObjectName(_fromUtf8("line_7"))
        self.formLayout_6.setWidget(1, QtGui.QFormLayout.SpanningRole, self.line_7)
        self.horizontalLayout_8 = QtGui.QHBoxLayout()
        self.horizontalLayout_8.setObjectName(_fromUtf8("horizontalLayout_8"))
        self.horizontalLayout_9 = QtGui.QHBoxLayout()
        self.horizontalLayout_9.setObjectName(_fromUtf8("horizontalLayout_9"))
        spacerItem8 = QtGui.QSpacerItem(68, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem8)
        self.today_lcd = QtGui.QLCDNumber(self.frame_5)
        self.today_lcd.setMinimumSize(QtCore.QSize(180, 81))
        self.today_lcd.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);\n"
"border: 0px solid black"))
        self.today_lcd.setObjectName(_fromUtf8("today_lcd"))
        self.horizontalLayout_9.addWidget(self.today_lcd)
        self.horizontalLayout_8.addLayout(self.horizontalLayout_9)
        spacerItem9 = QtGui.QSpacerItem(108, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_8.addItem(spacerItem9)
        self.formLayout_6.setLayout(2, QtGui.QFormLayout.FieldRole, self.horizontalLayout_8)
        self.label_10 = QtGui.QLabel(self.frame_5)
        font = QtGui.QFont()
        font.setPointSize(11)
        font.setBold(False)
        font.setWeight(50)
        self.label_10.setFont(font)
        self.label_10.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);\n"
"color: rgb(255, 255, 255);"))
        self.label_10.setObjectName(_fromUtf8("label_10"))
        self.formLayout_6.setWidget(0, QtGui.QFormLayout.FieldRole, self.label_10)
        self.horizontalLayout_10.addWidget(self.frame_5)
        self.gridLayout_2.addLayout(self.horizontalLayout_10, 2, 0, 1, 2)
        spacerItem10 = QtGui.QSpacerItem(1130, 99, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.gridLayout_2.addItem(spacerItem10, 3, 1, 1, 1)
        self.horizontalLayout_11 = QtGui.QHBoxLayout()
        self.horizontalLayout_11.setObjectName(_fromUtf8("horizontalLayout_11"))
        self.frame_8 = QtGui.QFrame(self.frame_2)
        self.frame_8.setMinimumSize(QtCore.QSize(557, 634))
        self.frame_8.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame_8.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_8.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_8.setObjectName(_fromUtf8("frame_8"))
        self.verticalLayout_3 = QtGui.QVBoxLayout(self.frame_8)
        self.verticalLayout_3.setObjectName(_fromUtf8("verticalLayout_3"))
        self.horizontalLayout_14 = QtGui.QHBoxLayout()
        self.horizontalLayout_14.setObjectName(_fromUtf8("horizontalLayout_14"))
        spacerItem11 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem11)
        self.year_bar = QtGui.QProgressBar(self.frame_8)
        self.year_bar.setMinimumSize(QtCore.QSize(42, 471))
        self.year_bar.setProperty("value", 24)
        self.year_bar.setOrientation(QtCore.Qt.Vertical)
        self.year_bar.setObjectName(_fromUtf8("year_bar"))
        self.horizontalLayout_14.addWidget(self.year_bar)
        spacerItem12 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_14.addItem(spacerItem12)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.verticalLayout = QtGui.QVBoxLayout()
        self.verticalLayout.setObjectName(_fromUtf8("verticalLayout"))
        self.horizontalLayout_15 = QtGui.QHBoxLayout()
        self.horizontalLayout_15.setObjectName(_fromUtf8("horizontalLayout_15"))
        spacerItem13 = QtGui.QSpacerItem(68, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem13)
        self.yearly_win_label = QtGui.QLabel(self.frame_8)
        self.yearly_win_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.yearly_win_label.setText(_fromUtf8(""))
        self.yearly_win_label.setObjectName(_fromUtf8("yearly_win_label"))
        self.horizontalLayout_15.addWidget(self.yearly_win_label)
        spacerItem14 = QtGui.QSpacerItem(78, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem14)
        self.verticalLayout.addLayout(self.horizontalLayout_15)
        self.horizontalLayout_24 = QtGui.QHBoxLayout()
        self.horizontalLayout_24.setObjectName(_fromUtf8("horizontalLayout_24"))
        spacerItem15 = QtGui.QSpacerItem(98, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem15)
        self.year_percent_label = QtGui.QLabel(self.frame_8)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.year_percent_label.setFont(font)
        self.year_percent_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.year_percent_label.setText(_fromUtf8(""))
        self.year_percent_label.setObjectName(_fromUtf8("year_percent_label"))
        self.horizontalLayout_24.addWidget(self.year_percent_label)
        spacerItem16 = QtGui.QSpacerItem(98, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_24.addItem(spacerItem16)
        self.verticalLayout.addLayout(self.horizontalLayout_24)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.horizontalLayout_11.addWidget(self.frame_8)
        self.frame_13 = QtGui.QFrame(self.frame_2)
        self.frame_13.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame_13.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_13.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_13.setObjectName(_fromUtf8("frame_13"))
        self.verticalLayout_9 = QtGui.QVBoxLayout(self.frame_13)
        self.verticalLayout_9.setObjectName(_fromUtf8("verticalLayout_9"))
        self.horizontalLayout_33 = QtGui.QHBoxLayout()
        self.horizontalLayout_33.setObjectName(_fromUtf8("horizontalLayout_33"))
        spacerItem17 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem17)
        self.month_bar = QtGui.QProgressBar(self.frame_13)
        self.month_bar.setMinimumSize(QtCore.QSize(42, 471))
        self.month_bar.setProperty("value", 24)
        self.month_bar.setOrientation(QtCore.Qt.Vertical)
        self.month_bar.setObjectName(_fromUtf8("month_bar"))
        self.horizontalLayout_33.addWidget(self.month_bar)
        spacerItem18 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_33.addItem(spacerItem18)
        self.verticalLayout_9.addLayout(self.horizontalLayout_33)
        self.verticalLayout_2 = QtGui.QVBoxLayout()
        self.verticalLayout_2.setObjectName(_fromUtf8("verticalLayout_2"))
        self.horizontalLayout_34 = QtGui.QHBoxLayout()
        self.horizontalLayout_34.setObjectName(_fromUtf8("horizontalLayout_34"))
        spacerItem19 = QtGui.QSpacerItem(68, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem19)
        self.monthly_win_label = QtGui.QLabel(self.frame_13)
        self.monthly_win_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);\n"
""))
        self.monthly_win_label.setText(_fromUtf8(""))
        self.monthly_win_label.setObjectName(_fromUtf8("monthly_win_label"))
        self.horizontalLayout_34.addWidget(self.monthly_win_label)
        spacerItem20 = QtGui.QSpacerItem(78, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_34.addItem(spacerItem20)
        self.verticalLayout_2.addLayout(self.horizontalLayout_34)
        self.horizontalLayout_35 = QtGui.QHBoxLayout()
        self.horizontalLayout_35.setObjectName(_fromUtf8("horizontalLayout_35"))
        spacerItem21 = QtGui.QSpacerItem(98, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem21)
        self.month_percent_label = QtGui.QLabel(self.frame_13)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.month_percent_label.setFont(font)
        self.month_percent_label.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.month_percent_label.setText(_fromUtf8(""))
        self.month_percent_label.setObjectName(_fromUtf8("month_percent_label"))
        self.horizontalLayout_35.addWidget(self.month_percent_label)
        spacerItem22 = QtGui.QSpacerItem(98, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_35.addItem(spacerItem22)
        self.verticalLayout_2.addLayout(self.horizontalLayout_35)
        self.verticalLayout_9.addLayout(self.verticalLayout_2)
        self.horizontalLayout_11.addWidget(self.frame_13)
        self.gridLayout_2.addLayout(self.horizontalLayout_11, 4, 0, 1, 2)
        self.horizontalLayout.addWidget(self.frame_2)
        self.frame = QtGui.QFrame(self.centralwidget)
        self.frame.setMinimumSize(QtCore.QSize(0, 0))
        self.frame.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtGui.QFrame.Raised)
        self.frame.setObjectName(_fromUtf8("frame"))
        self.formLayout_3 = QtGui.QFormLayout(self.frame)
        self.formLayout_3.setObjectName(_fromUtf8("formLayout_3"))
        self.label_5 = QtGui.QLabel(self.frame)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_5.setFont(font)
        self.label_5.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_5.setObjectName(_fromUtf8("label_5"))
        self.formLayout_3.setWidget(0, QtGui.QFormLayout.LabelRole, self.label_5)
        self.frame_9 = QtGui.QFrame(self.frame)
        self.frame_9.setMinimumSize(QtCore.QSize(1221, 351))
        self.frame_9.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame_9.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_9.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_9.setObjectName(_fromUtf8("frame_9"))
        self.label_6 = QtGui.QLabel(self.frame_9)
        self.label_6.setGeometry(QtCore.QRect(24, 24, 321, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_6.setObjectName(_fromUtf8("label_6"))
        self.line = QtGui.QFrame(self.frame_9)
        self.line.setGeometry(QtCore.QRect(24, 87, 570, 16))
        self.line.setLineWidth(3)
        self.line.setFrameShape(QtGui.QFrame.HLine)
        self.line.setFrameShadow(QtGui.QFrame.Sunken)
        self.line.setObjectName(_fromUtf8("line"))
        self.layoutWidget = QtGui.QWidget(self.frame_9)
        self.layoutWidget.setGeometry(QtCore.QRect(23, 120, 578, 240))
        self.layoutWidget.setObjectName(_fromUtf8("layoutWidget"))
        self.formLayout_10 = QtGui.QFormLayout(self.layoutWidget)
        self.formLayout_10.setObjectName(_fromUtf8("formLayout_10"))
        self.verticalLayout_6 = QtGui.QVBoxLayout()
        self.verticalLayout_6.setObjectName(_fromUtf8("verticalLayout_6"))
        self.horizontalLayout_19 = QtGui.QHBoxLayout()
        self.horizontalLayout_19.setObjectName(_fromUtf8("horizontalLayout_19"))
        spacerItem23 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem23)
        self.horizontalLayout_16 = QtGui.QHBoxLayout()
        self.horizontalLayout_16.setObjectName(_fromUtf8("horizontalLayout_16"))
        self.label_7 = QtGui.QLabel(self.layoutWidget)
        self.label_7.setMinimumSize(QtCore.QSize(143, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_7.setFont(font)
        self.label_7.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_7.setObjectName(_fromUtf8("label_7"))
        self.horizontalLayout_16.addWidget(self.label_7)
        self.entry_input = QtGui.QLineEdit(self.layoutWidget)
        self.entry_input.setMinimumSize(QtCore.QSize(295, 40))
        self.entry_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.entry_input.setObjectName(_fromUtf8("entry_input"))
        self.horizontalLayout_16.addWidget(self.entry_input)
        self.horizontalLayout_19.addLayout(self.horizontalLayout_16)
        self.verticalLayout_6.addLayout(self.horizontalLayout_19)
        self.horizontalLayout_20 = QtGui.QHBoxLayout()
        self.horizontalLayout_20.setObjectName(_fromUtf8("horizontalLayout_20"))
        spacerItem24 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_20.addItem(spacerItem24)
        self.horizontalLayout_17 = QtGui.QHBoxLayout()
        self.horizontalLayout_17.setObjectName(_fromUtf8("horizontalLayout_17"))
        self.label_11 = QtGui.QLabel(self.layoutWidget)
        self.label_11.setMinimumSize(QtCore.QSize(154, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_11.setFont(font)
        self.label_11.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_11.setObjectName(_fromUtf8("label_11"))
        self.horizontalLayout_17.addWidget(self.label_11)
        self.target_input = QtGui.QLineEdit(self.layoutWidget)
        self.target_input.setMinimumSize(QtCore.QSize(295, 40))
        self.target_input.setMaximumSize(QtCore.QSize(295, 16777215))
        self.target_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.target_input.setObjectName(_fromUtf8("target_input"))
        self.horizontalLayout_17.addWidget(self.target_input)
        self.horizontalLayout_20.addLayout(self.horizontalLayout_17)
        self.verticalLayout_6.addLayout(self.horizontalLayout_20)
        self.horizontalLayout_21 = QtGui.QHBoxLayout()
        self.horizontalLayout_21.setObjectName(_fromUtf8("horizontalLayout_21"))
        spacerItem25 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem25)
        self.horizontalLayout_18 = QtGui.QHBoxLayout()
        self.horizontalLayout_18.setObjectName(_fromUtf8("horizontalLayout_18"))
        self.label_12 = QtGui.QLabel(self.layoutWidget)
        self.label_12.setMinimumSize(QtCore.QSize(129, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_12.setFont(font)
        self.label_12.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_12.setObjectName(_fromUtf8("label_12"))
        self.horizontalLayout_18.addWidget(self.label_12)
        self.stop_input = QtGui.QLineEdit(self.layoutWidget)
        self.stop_input.setMinimumSize(QtCore.QSize(296, 40))
        self.stop_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.stop_input.setObjectName(_fromUtf8("stop_input"))
        self.horizontalLayout_18.addWidget(self.stop_input)
        self.horizontalLayout_21.addLayout(self.horizontalLayout_18)
        self.verticalLayout_6.addLayout(self.horizontalLayout_21)
        self.formLayout_10.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_6)
        self.horizontalLayout_22 = QtGui.QHBoxLayout()
        self.horizontalLayout_22.setObjectName(_fromUtf8("horizontalLayout_22"))
        spacerItem26 = QtGui.QSpacerItem(78, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem26)
        self.rr_btn = QtGui.QPushButton(self.layoutWidget)
        self.rr_btn.setStyleSheet(_fromUtf8("background-color: rgb(211, 211, 211);"))
        self.rr_btn.setObjectName(_fromUtf8("rr_btn"))
        self.horizontalLayout_22.addWidget(self.rr_btn)
        spacerItem27 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_22.addItem(spacerItem27)
        self.formLayout_10.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_22)
        self.layoutWidget1 = QtGui.QWidget(self.frame_9)
        self.layoutWidget1.setGeometry(QtCore.QRect(597, 23, 600, 359))
        self.layoutWidget1.setObjectName(_fromUtf8("layoutWidget1"))
        self.horizontalLayout_43 = QtGui.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_43.setObjectName(_fromUtf8("horizontalLayout_43"))
        spacerItem28 = QtGui.QSpacerItem(152, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_43.addItem(spacerItem28)
        self.ratio_display = QtGui.QLabel(self.layoutWidget1)
        self.ratio_display.setMinimumSize(QtCore.QSize(431, 357))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.ratio_display.setFont(font)
        self.ratio_display.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);\n"
"color: rgb(255, 255, 255);"))
        self.ratio_display.setText(_fromUtf8(""))
        self.ratio_display.setObjectName(_fromUtf8("ratio_display"))
        self.horizontalLayout_43.addWidget(self.ratio_display)
        self.formLayout_3.setWidget(1, QtGui.QFormLayout.LabelRole, self.frame_9)
        spacerItem29 = QtGui.QSpacerItem(20, 40, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.formLayout_3.setItem(2, QtGui.QFormLayout.LabelRole, spacerItem29)
        self.frame_10 = QtGui.QFrame(self.frame)
        self.frame_10.setMinimumSize(QtCore.QSize(1221, 351))
        self.frame_10.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.frame_10.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_10.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_10.setObjectName(_fromUtf8("frame_10"))
        self.layoutWidget2 = QtGui.QWidget(self.frame_10)
        self.layoutWidget2.setGeometry(QtCore.QRect(23, 119, 586, 261))
        self.layoutWidget2.setObjectName(_fromUtf8("layoutWidget2"))
        self.formLayout = QtGui.QFormLayout(self.layoutWidget2)
        self.formLayout.setObjectName(_fromUtf8("formLayout"))
        self.verticalLayout_7 = QtGui.QVBoxLayout()
        self.verticalLayout_7.setObjectName(_fromUtf8("verticalLayout_7"))
        self.horizontalLayout_25 = QtGui.QHBoxLayout()
        self.horizontalLayout_25.setObjectName(_fromUtf8("horizontalLayout_25"))
        spacerItem30 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem30)
        self.horizontalLayout_26 = QtGui.QHBoxLayout()
        self.horizontalLayout_26.setObjectName(_fromUtf8("horizontalLayout_26"))
        self.label_15 = QtGui.QLabel(self.layoutWidget2)
        self.label_15.setMinimumSize(QtCore.QSize(190, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_15.setFont(font)
        self.label_15.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_15.setObjectName(_fromUtf8("label_15"))
        self.horizontalLayout_26.addWidget(self.label_15)
        self.before_val_input = QtGui.QLineEdit(self.layoutWidget2)
        self.before_val_input.setMinimumSize(QtCore.QSize(295, 40))
        self.before_val_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.before_val_input.setObjectName(_fromUtf8("before_val_input"))
        self.horizontalLayout_26.addWidget(self.before_val_input)
        self.horizontalLayout_25.addLayout(self.horizontalLayout_26)
        self.verticalLayout_7.addLayout(self.horizontalLayout_25)
        self.horizontalLayout_27 = QtGui.QHBoxLayout()
        self.horizontalLayout_27.setObjectName(_fromUtf8("horizontalLayout_27"))
        spacerItem31 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem31)
        self.horizontalLayout_28 = QtGui.QHBoxLayout()
        self.horizontalLayout_28.setObjectName(_fromUtf8("horizontalLayout_28"))
        self.label_16 = QtGui.QLabel(self.layoutWidget2)
        self.label_16.setMinimumSize(QtCore.QSize(210, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_16.setFont(font)
        self.label_16.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_16.setObjectName(_fromUtf8("label_16"))
        self.horizontalLayout_28.addWidget(self.label_16)
        self.current_val_input = QtGui.QLineEdit(self.layoutWidget2)
        self.current_val_input.setMinimumSize(QtCore.QSize(295, 40))
        self.current_val_input.setMaximumSize(QtCore.QSize(295, 16777215))
        self.current_val_input.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.current_val_input.setObjectName(_fromUtf8("current_val_input"))
        self.horizontalLayout_28.addWidget(self.current_val_input)
        self.horizontalLayout_27.addLayout(self.horizontalLayout_28)
        self.verticalLayout_7.addLayout(self.horizontalLayout_27)
        self.formLayout.setLayout(0, QtGui.QFormLayout.LabelRole, self.verticalLayout_7)
        self.horizontalLayout_23 = QtGui.QHBoxLayout()
        self.horizontalLayout_23.setObjectName(_fromUtf8("horizontalLayout_23"))
        spacerItem32 = QtGui.QSpacerItem(148, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem32)
        self.percent_move_btn = QtGui.QPushButton(self.layoutWidget2)
        self.percent_move_btn.setStyleSheet(_fromUtf8("background-color: rgb(211, 211, 211);"))
        self.percent_move_btn.setObjectName(_fromUtf8("percent_move_btn"))
        self.horizontalLayout_23.addWidget(self.percent_move_btn)
        spacerItem33 = QtGui.QSpacerItem(48, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem33)
        self.formLayout.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_23)
        self.label_14 = QtGui.QLabel(self.frame_10)
        self.label_14.setGeometry(QtCore.QRect(24, 24, 301, 48))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_14.setFont(font)
        self.label_14.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_14.setObjectName(_fromUtf8("label_14"))
        self.line_2 = QtGui.QFrame(self.frame_10)
        self.line_2.setGeometry(QtCore.QRect(24, 87, 570, 16))
        self.line_2.setLineWidth(3)
        self.line_2.setFrameShape(QtGui.QFrame.HLine)
        self.line_2.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_2.setObjectName(_fromUtf8("line_2"))
        self.layoutWidget3 = QtGui.QWidget(self.frame_10)
        self.layoutWidget3.setGeometry(QtCore.QRect(625, 24, 566, 359))
        self.layoutWidget3.setObjectName(_fromUtf8("layoutWidget3"))
        self.horizontalLayout_30 = QtGui.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_30.setObjectName(_fromUtf8("horizontalLayout_30"))
        spacerItem34 = QtGui.QSpacerItem(118, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_30.addItem(spacerItem34)
        self.percent_move_display = QtGui.QLabel(self.layoutWidget3)
        self.percent_move_display.setMinimumSize(QtCore.QSize(431, 357))
        font = QtGui.QFont()
        font.setPointSize(24)
        self.percent_move_display.setFont(font)
        self.percent_move_display.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);\n"
"color: rgb(255, 255, 255);"))
        self.percent_move_display.setText(_fromUtf8(""))
        self.percent_move_display.setObjectName(_fromUtf8("percent_move_display"))
        self.horizontalLayout_30.addWidget(self.percent_move_display)
        self.formLayout_3.setWidget(3, QtGui.QFormLayout.LabelRole, self.frame_10)
        self.frame_9.raise_()
        self.frame_10.raise_()
        self.label_5.raise_()
        self.horizontalLayout.addWidget(self.frame)
        self.gridLayout.addLayout(self.horizontalLayout, 0, 0, 1, 1)
        self.tabWidget = QtGui.QTabWidget(self.centralwidget)
        self.tabWidget.setMinimumSize(QtCore.QSize(0, 0))
        self.tabWidget.setMaximumSize(QtCore.QSize(16777215, 16777215))
        self.tabWidget.setStyleSheet(_fromUtf8("background-color: rgb(78, 86, 88);"))
        self.tabWidget.setObjectName(_fromUtf8("tabWidget"))
        self.tab = QtGui.QWidget()
        self.tab.setObjectName(_fromUtf8("tab"))
        self.verticalLayout_12 = QtGui.QVBoxLayout(self.tab)
        self.verticalLayout_12.setObjectName(_fromUtf8("verticalLayout_12"))
        self.frame_7 = QtGui.QFrame(self.tab)
        self.frame_7.setMinimumSize(QtCore.QSize(0, 360))
        self.frame_7.setMaximumSize(QtCore.QSize(1709, 600))
        self.frame_7.setFrameShape(QtGui.QFrame.StyledPanel)
        self.frame_7.setFrameShadow(QtGui.QFrame.Raised)
        self.frame_7.setObjectName(_fromUtf8("frame_7"))
        self.formLayout_2 = QtGui.QFormLayout(self.frame_7)
        self.formLayout_2.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_2.setObjectName(_fromUtf8("formLayout_2"))
        self.horizontalLayout_12 = QtGui.QHBoxLayout()
        self.horizontalLayout_12.setObjectName(_fromUtf8("horizontalLayout_12"))
        self.label_23 = QtGui.QLabel(self.frame_7)
        self.label_23.setMinimumSize(QtCore.QSize(222, 41))
        self.label_23.setMaximumSize(QtCore.QSize(222, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_23.setFont(font)
        self.label_23.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_23.setObjectName(_fromUtf8("label_23"))
        self.horizontalLayout_12.addWidget(self.label_23)
        spacerItem35 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem35)
        self.year_switch_btn = QtGui.QPushButton(self.frame_7)
        self.year_switch_btn.setMinimumSize(QtCore.QSize(41, 41))
        self.year_switch_btn.setMaximumSize(QtCore.QSize(41, 41))
        self.year_switch_btn.setStyleSheet(_fromUtf8("background-color: rgb(209, 209, 209);"))
        self.year_switch_btn.setObjectName(_fromUtf8("year_switch_btn"))
        self.horizontalLayout_12.addWidget(self.year_switch_btn)
        self.month_switch_btn = QtGui.QPushButton(self.frame_7)
        self.month_switch_btn.setMinimumSize(QtCore.QSize(41, 41))
        self.month_switch_btn.setMaximumSize(QtCore.QSize(41, 41))
        self.month_switch_btn.setStyleSheet(_fromUtf8("background-color: rgb(209, 209, 209);"))
        self.month_switch_btn.setObjectName(_fromUtf8("month_switch_btn"))
        self.horizontalLayout_12.addWidget(self.month_switch_btn)
        self.label_18 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_18.setFont(font)
        self.label_18.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_18.setObjectName(_fromUtf8("label_18"))
        self.horizontalLayout_12.addWidget(self.label_18)
        spacerItem36 = QtGui.QSpacerItem(208, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_12.addItem(spacerItem36)
        self.formLayout_2.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_12)
        self.horizontalLayout_58 = QtGui.QHBoxLayout()
        self.horizontalLayout_58.setObjectName(_fromUtf8("horizontalLayout_58"))
        self.line_4 = QtGui.QFrame(self.frame_7)
        self.line_4.setMinimumSize(QtCore.QSize(350, 16))
        self.line_4.setLineWidth(3)
        self.line_4.setFrameShape(QtGui.QFrame.HLine)
        self.line_4.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_4.setObjectName(_fromUtf8("line_4"))
        self.horizontalLayout_58.addWidget(self.line_4)
        spacerItem37 = QtGui.QSpacerItem(38, 17, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_58.addItem(spacerItem37)
        self.line_17 = QtGui.QFrame(self.frame_7)
        self.line_17.setMinimumSize(QtCore.QSize(1228, 20))
        font = QtGui.QFont()
        font.setPointSize(8)
        self.line_17.setFont(font)
        self.line_17.setLineWidth(3)
        self.line_17.setMidLineWidth(0)
        self.line_17.setFrameShape(QtGui.QFrame.HLine)
        self.line_17.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_17.setObjectName(_fromUtf8("line_17"))
        self.horizontalLayout_58.addWidget(self.line_17)
        self.formLayout_2.setLayout(1, QtGui.QFormLayout.LabelRole, self.horizontalLayout_58)
        self.horizontalLayout_3 = QtGui.QHBoxLayout()
        self.horizontalLayout_3.setObjectName(_fromUtf8("horizontalLayout_3"))
        self.verticalLayout_4 = QtGui.QVBoxLayout()
        self.verticalLayout_4.setObjectName(_fromUtf8("verticalLayout_4"))
        self.formLayout_12 = QtGui.QFormLayout()
        self.formLayout_12.setFieldGrowthPolicy(QtGui.QFormLayout.AllNonFixedFieldsGrow)
        self.formLayout_12.setObjectName(_fromUtf8("formLayout_12"))
        self.horizontalLayout_45 = QtGui.QHBoxLayout()
        self.horizontalLayout_45.setObjectName(_fromUtf8("horizontalLayout_45"))
        self.label_25 = QtGui.QLabel(self.frame_7)
        self.label_25.setMinimumSize(QtCore.QSize(230, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_25.setFont(font)
        self.label_25.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_25.setObjectName(_fromUtf8("label_25"))
        self.horizontalLayout_45.addWidget(self.label_25)
        self.trade_outcome_box = QtGui.QComboBox(self.frame_7)
        self.trade_outcome_box.setMinimumSize(QtCore.QSize(90, 40))
        self.trade_outcome_box.setMaximumSize(QtCore.QSize(81, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.trade_outcome_box.setFont(font)
        self.trade_outcome_box.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.trade_outcome_box.setObjectName(_fromUtf8("trade_outcome_box"))
        self.trade_outcome_box.addItem(_fromUtf8(""))
        self.trade_outcome_box.addItem(_fromUtf8(""))
        self.horizontalLayout_45.addWidget(self.trade_outcome_box)
        self.formLayout_12.setLayout(0, QtGui.QFormLayout.LabelRole, self.horizontalLayout_45)
        self.verticalLayout_13 = QtGui.QVBoxLayout()
        self.verticalLayout_13.setObjectName(_fromUtf8("verticalLayout_13"))
        self.label_27 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_27.setFont(font)
        self.label_27.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_27.setObjectName(_fromUtf8("label_27"))
        self.verticalLayout_13.addWidget(self.label_27)
        self.reason_box = QtGui.QComboBox(self.frame_7)
        self.reason_box.setMinimumSize(QtCore.QSize(0, 35))
        self.reason_box.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.reason_box.setObjectName(_fromUtf8("reason_box"))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.reason_box.addItem(_fromUtf8(""))
        self.verticalLayout_13.addWidget(self.reason_box)
        self.formLayout_12.setLayout(1, QtGui.QFormLayout.LabelRole, self.verticalLayout_13)
        self.verticalLayout_4.addLayout(self.formLayout_12)
        self.add_trade_btn = QtGui.QPushButton(self.frame_7)
        self.add_trade_btn.setStyleSheet(_fromUtf8("background-color: rgb(211, 211, 211);"))
        self.add_trade_btn.setObjectName(_fromUtf8("add_trade_btn"))
        self.verticalLayout_4.addWidget(self.add_trade_btn)
        self.horizontalLayout_3.addLayout(self.verticalLayout_4)
        self.line_16 = QtGui.QFrame(self.frame_7)
        self.line_16.setMinimumSize(QtCore.QSize(20, 231))
        self.line_16.setMaximumSize(QtCore.QSize(20, 231))
        self.line_16.setLineWidth(3)
        self.line_16.setFrameShape(QtGui.QFrame.VLine)
        self.line_16.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_16.setObjectName(_fromUtf8("line_16"))
        self.horizontalLayout_3.addWidget(self.line_16)
        self.verticalLayout_11 = QtGui.QVBoxLayout()
        self.verticalLayout_11.setObjectName(_fromUtf8("verticalLayout_11"))
        self.horizontalLayout_2 = QtGui.QHBoxLayout()
        self.horizontalLayout_2.setObjectName(_fromUtf8("horizontalLayout_2"))
        self.verticalLayout_5 = QtGui.QVBoxLayout()
        self.verticalLayout_5.setObjectName(_fromUtf8("verticalLayout_5"))
        self.horizontalLayout_50 = QtGui.QHBoxLayout()
        self.horizontalLayout_50.setObjectName(_fromUtf8("horizontalLayout_50"))
        self.label_33 = QtGui.QLabel(self.frame_7)
        self.label_33.setMinimumSize(QtCore.QSize(267, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_33.setFont(font)
        self.label_33.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_33.setObjectName(_fromUtf8("label_33"))
        self.horizontalLayout_50.addWidget(self.label_33)
        self.poor_rr_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.poor_rr_display.setFont(font)
        self.poor_rr_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.poor_rr_display.setText(_fromUtf8(""))
        self.poor_rr_display.setObjectName(_fromUtf8("poor_rr_display"))
        self.horizontalLayout_50.addWidget(self.poor_rr_display)
        self.verticalLayout_5.addLayout(self.horizontalLayout_50)
        spacerItem38 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem38)
        self.horizontalLayout_51 = QtGui.QHBoxLayout()
        self.horizontalLayout_51.setObjectName(_fromUtf8("horizontalLayout_51"))
        self.label_35 = QtGui.QLabel(self.frame_7)
        self.label_35.setMinimumSize(QtCore.QSize(267, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_35.setFont(font)
        self.label_35.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_35.setObjectName(_fromUtf8("label_35"))
        self.horizontalLayout_51.addWidget(self.label_35)
        self.entered_soon_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entered_soon_display.setFont(font)
        self.entered_soon_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.entered_soon_display.setText(_fromUtf8(""))
        self.entered_soon_display.setObjectName(_fromUtf8("entered_soon_display"))
        self.horizontalLayout_51.addWidget(self.entered_soon_display)
        self.verticalLayout_5.addLayout(self.horizontalLayout_51)
        spacerItem39 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_5.addItem(spacerItem39)
        self.horizontalLayout_52 = QtGui.QHBoxLayout()
        self.horizontalLayout_52.setObjectName(_fromUtf8("horizontalLayout_52"))
        self.label_37 = QtGui.QLabel(self.frame_7)
        self.label_37.setMaximumSize(QtCore.QSize(256, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_37.setFont(font)
        self.label_37.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_37.setObjectName(_fromUtf8("label_37"))
        self.horizontalLayout_52.addWidget(self.label_37)
        self.entered_late_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entered_late_display.setFont(font)
        self.entered_late_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.entered_late_display.setText(_fromUtf8(""))
        self.entered_late_display.setObjectName(_fromUtf8("entered_late_display"))
        self.horizontalLayout_52.addWidget(self.entered_late_display)
        self.verticalLayout_5.addLayout(self.horizontalLayout_52)
        self.horizontalLayout_2.addLayout(self.verticalLayout_5)
        spacerItem40 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem40)
        self.verticalLayout_8 = QtGui.QVBoxLayout()
        self.verticalLayout_8.setObjectName(_fromUtf8("verticalLayout_8"))
        self.horizontalLayout_46 = QtGui.QHBoxLayout()
        self.horizontalLayout_46.setObjectName(_fromUtf8("horizontalLayout_46"))
        self.label_39 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_39.setFont(font)
        self.label_39.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_39.setObjectName(_fromUtf8("label_39"))
        self.horizontalLayout_46.addWidget(self.label_39)
        self.exited_soon_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exited_soon_display.setFont(font)
        self.exited_soon_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.exited_soon_display.setText(_fromUtf8(""))
        self.exited_soon_display.setObjectName(_fromUtf8("exited_soon_display"))
        self.horizontalLayout_46.addWidget(self.exited_soon_display)
        self.verticalLayout_8.addLayout(self.horizontalLayout_46)
        spacerItem41 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem41)
        self.horizontalLayout_49 = QtGui.QHBoxLayout()
        self.horizontalLayout_49.setObjectName(_fromUtf8("horizontalLayout_49"))
        self.label_40 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_40.setFont(font)
        self.label_40.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_40.setObjectName(_fromUtf8("label_40"))
        self.horizontalLayout_49.addWidget(self.label_40)
        self.exited_late_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exited_late_display.setFont(font)
        self.exited_late_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.exited_late_display.setText(_fromUtf8(""))
        self.exited_late_display.setObjectName(_fromUtf8("exited_late_display"))
        self.horizontalLayout_49.addWidget(self.exited_late_display)
        self.verticalLayout_8.addLayout(self.horizontalLayout_49)
        spacerItem42 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_8.addItem(spacerItem42)
        self.horizontalLayout_53 = QtGui.QHBoxLayout()
        self.horizontalLayout_53.setObjectName(_fromUtf8("horizontalLayout_53"))
        self.label_41 = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_41.setFont(font)
        self.label_41.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_41.setObjectName(_fromUtf8("label_41"))
        self.horizontalLayout_53.addWidget(self.label_41)
        self.unplanned_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unplanned_display.setFont(font)
        self.unplanned_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.unplanned_display.setText(_fromUtf8(""))
        self.unplanned_display.setObjectName(_fromUtf8("unplanned_display"))
        self.horizontalLayout_53.addWidget(self.unplanned_display)
        self.verticalLayout_8.addLayout(self.horizontalLayout_53)
        self.horizontalLayout_2.addLayout(self.verticalLayout_8)
        spacerItem43 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem43)
        self.verticalLayout_10 = QtGui.QVBoxLayout()
        self.verticalLayout_10.setObjectName(_fromUtf8("verticalLayout_10"))
        self.horizontalLayout_54 = QtGui.QHBoxLayout()
        self.horizontalLayout_54.setObjectName(_fromUtf8("horizontalLayout_54"))
        self.label_42 = QtGui.QLabel(self.frame_7)
        self.label_42.setMaximumSize(QtCore.QSize(215, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_42.setFont(font)
        self.label_42.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_42.setObjectName(_fromUtf8("label_42"))
        self.horizontalLayout_54.addWidget(self.label_42)
        self.stop_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_display.setFont(font)
        self.stop_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);\n"
""))
        self.stop_display.setText(_fromUtf8(""))
        self.stop_display.setObjectName(_fromUtf8("stop_display"))
        self.horizontalLayout_54.addWidget(self.stop_display)
        self.verticalLayout_10.addLayout(self.horizontalLayout_54)
        spacerItem44 = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem44)
        self.horizontalLayout_55 = QtGui.QHBoxLayout()
        self.horizontalLayout_55.setObjectName(_fromUtf8("horizontalLayout_55"))
        self.label_43 = QtGui.QLabel(self.frame_7)
        self.label_43.setMinimumSize(QtCore.QSize(276, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_43.setFont(font)
        self.label_43.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_43.setObjectName(_fromUtf8("label_43"))
        self.horizontalLayout_55.addWidget(self.label_43)
        self.too_large_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.too_large_display.setFont(font)
        self.too_large_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.too_large_display.setText(_fromUtf8(""))
        self.too_large_display.setObjectName(_fromUtf8("too_large_display"))
        self.horizontalLayout_55.addWidget(self.too_large_display)
        self.verticalLayout_10.addLayout(self.horizontalLayout_55)
        spacerItem45 = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_10.addItem(spacerItem45)
        self.horizontalLayout_56 = QtGui.QHBoxLayout()
        self.horizontalLayout_56.setObjectName(_fromUtf8("horizontalLayout_56"))
        self.label_44 = QtGui.QLabel(self.frame_7)
        self.label_44.setMinimumSize(QtCore.QSize(150, 34))
        self.label_44.setMaximumSize(QtCore.QSize(126, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_44.setFont(font)
        self.label_44.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_44.setObjectName(_fromUtf8("label_44"))
        self.horizontalLayout_56.addWidget(self.label_44)
        self.hesitated_display = QtGui.QLabel(self.frame_7)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hesitated_display.setFont(font)
        self.hesitated_display.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.hesitated_display.setText(_fromUtf8(""))
        self.hesitated_display.setObjectName(_fromUtf8("hesitated_display"))
        self.horizontalLayout_56.addWidget(self.hesitated_display)
        self.verticalLayout_10.addLayout(self.horizontalLayout_56)
        self.horizontalLayout_2.addLayout(self.verticalLayout_10)
        self.verticalLayout_11.addLayout(self.horizontalLayout_2)
        spacerItem46 = QtGui.QSpacerItem(17, 13, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_11.addItem(spacerItem46)
        self.horizontalLayout_3.addLayout(self.verticalLayout_11)
        self.formLayout_2.setLayout(2, QtGui.QFormLayout.LabelRole, self.horizontalLayout_3)
        self.verticalLayout_12.addWidget(self.frame_7)
        self.tabWidget.addTab(self.tab, _fromUtf8(""))
        self.tab_2 = QtGui.QWidget()
        self.tab_2.setObjectName(_fromUtf8("tab_2"))
        self.label_24 = QtGui.QLabel(self.tab_2)
        self.label_24.setGeometry(QtCore.QRect(30, 30, 161, 41))
        self.label_24.setMinimumSize(QtCore.QSize(0, 41))
        self.label_24.setMaximumSize(QtCore.QSize(222, 41))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_24.setFont(font)
        self.label_24.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_24.setObjectName(_fromUtf8("label_24"))
        self.line_3 = QtGui.QFrame(self.tab_2)
        self.line_3.setGeometry(QtCore.QRect(30, 80, 261, 16))
        self.line_3.setLineWidth(3)
        self.line_3.setFrameShape(QtGui.QFrame.HLine)
        self.line_3.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_3.setObjectName(_fromUtf8("line_3"))
        self.label_2 = QtGui.QLabel(self.tab_2)
        self.label_2.setGeometry(QtCore.QRect(31, 131, 102, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_2.setObjectName(_fromUtf8("label_2"))
        self.past_month_menu = QtGui.QComboBox(self.tab_2)
        self.past_month_menu.setGeometry(QtCore.QRect(149, 135, 90, 38))
        self.past_month_menu.setMaximumSize(QtCore.QSize(90, 16777215))
        self.past_month_menu.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.past_month_menu.setObjectName(_fromUtf8("past_month_menu"))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.past_month_menu.addItem(_fromUtf8(""))
        self.label_3 = QtGui.QLabel(self.tab_2)
        self.label_3.setGeometry(QtCore.QRect(34, 200, 101, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName(_fromUtf8("label_3"))
        self.past_year_entry = QtGui.QLineEdit(self.tab_2)
        self.past_year_entry.setGeometry(QtCore.QRect(149, 200, 130, 40))
        self.past_year_entry.setMaximumSize(QtCore.QSize(130, 16777215))
        self.past_year_entry.setStyleSheet(_fromUtf8("background-color: rgb(255, 255, 255);"))
        self.past_year_entry.setObjectName(_fromUtf8("past_year_entry"))
        self.past_stats_search_btn = QtGui.QPushButton(self.tab_2)
        self.past_stats_search_btn.setGeometry(QtCore.QRect(90, 270, 187, 57))
        self.past_stats_search_btn.setStyleSheet(_fromUtf8("background-color: rgb(209, 209, 209);"))
        self.past_stats_search_btn.setObjectName(_fromUtf8("past_stats_search_btn"))
        self.line_8 = QtGui.QFrame(self.tab_2)
        self.line_8.setGeometry(QtCore.QRect(313, 130, 20, 201))
        self.line_8.setLineWidth(3)
        self.line_8.setFrameShape(QtGui.QFrame.VLine)
        self.line_8.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_8.setObjectName(_fromUtf8("line_8"))
        self.line_9 = QtGui.QFrame(self.tab_2)
        self.line_9.setGeometry(QtCore.QRect(350, 80, 1661, 16))
        self.line_9.setLineWidth(3)
        self.line_9.setFrameShape(QtGui.QFrame.HLine)
        self.line_9.setFrameShadow(QtGui.QFrame.Sunken)
        self.line_9.setObjectName(_fromUtf8("line_9"))
        self.label_4 = QtGui.QLabel(self.tab_2)
        self.label_4.setGeometry(QtCore.QRect(360, 20, 1211, 61))
        font = QtGui.QFont()
        font.setPointSize(15)
        self.label_4.setFont(font)
        self.label_4.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_4.setObjectName(_fromUtf8("label_4"))
        self.layoutWidget_3 = QtGui.QWidget(self.tab_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(370, 120, 1159, 219))
        self.layoutWidget_3.setObjectName(_fromUtf8("layoutWidget_3"))
        self.verticalLayout_15 = QtGui.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_15.setObjectName(_fromUtf8("verticalLayout_15"))
        self.horizontalLayout_29 = QtGui.QHBoxLayout()
        self.horizontalLayout_29.setObjectName(_fromUtf8("horizontalLayout_29"))
        self.verticalLayout_16 = QtGui.QVBoxLayout()
        self.verticalLayout_16.setObjectName(_fromUtf8("verticalLayout_16"))
        self.horizontalLayout_57 = QtGui.QHBoxLayout()
        self.horizontalLayout_57.setObjectName(_fromUtf8("horizontalLayout_57"))
        self.label_34 = QtGui.QLabel(self.layoutWidget_3)
        self.label_34.setMinimumSize(QtCore.QSize(267, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_34.setFont(font)
        self.label_34.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_34.setObjectName(_fromUtf8("label_34"))
        self.horizontalLayout_57.addWidget(self.label_34)
        self.poor_rr_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.poor_rr_display_2.setFont(font)
        self.poor_rr_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.poor_rr_display_2.setText(_fromUtf8(""))
        self.poor_rr_display_2.setObjectName(_fromUtf8("poor_rr_display_2"))
        self.horizontalLayout_57.addWidget(self.poor_rr_display_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_57)
        spacerItem47 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem47)
        self.horizontalLayout_59 = QtGui.QHBoxLayout()
        self.horizontalLayout_59.setObjectName(_fromUtf8("horizontalLayout_59"))
        self.label_36 = QtGui.QLabel(self.layoutWidget_3)
        self.label_36.setMinimumSize(QtCore.QSize(267, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_36.setFont(font)
        self.label_36.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_36.setObjectName(_fromUtf8("label_36"))
        self.horizontalLayout_59.addWidget(self.label_36)
        self.entered_soon_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entered_soon_display_2.setFont(font)
        self.entered_soon_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.entered_soon_display_2.setText(_fromUtf8(""))
        self.entered_soon_display_2.setObjectName(_fromUtf8("entered_soon_display_2"))
        self.horizontalLayout_59.addWidget(self.entered_soon_display_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_59)
        spacerItem48 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_16.addItem(spacerItem48)
        self.horizontalLayout_60 = QtGui.QHBoxLayout()
        self.horizontalLayout_60.setObjectName(_fromUtf8("horizontalLayout_60"))
        self.label_38 = QtGui.QLabel(self.layoutWidget_3)
        self.label_38.setMaximumSize(QtCore.QSize(256, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_38.setFont(font)
        self.label_38.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_38.setObjectName(_fromUtf8("label_38"))
        self.horizontalLayout_60.addWidget(self.label_38)
        self.entered_late_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.entered_late_display_2.setFont(font)
        self.entered_late_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.entered_late_display_2.setText(_fromUtf8(""))
        self.entered_late_display_2.setObjectName(_fromUtf8("entered_late_display_2"))
        self.horizontalLayout_60.addWidget(self.entered_late_display_2)
        self.verticalLayout_16.addLayout(self.horizontalLayout_60)
        self.horizontalLayout_29.addLayout(self.verticalLayout_16)
        spacerItem49 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem49)
        self.verticalLayout_17 = QtGui.QVBoxLayout()
        self.verticalLayout_17.setObjectName(_fromUtf8("verticalLayout_17"))
        self.horizontalLayout_47 = QtGui.QHBoxLayout()
        self.horizontalLayout_47.setObjectName(_fromUtf8("horizontalLayout_47"))
        self.label_45 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_45.setFont(font)
        self.label_45.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_45.setObjectName(_fromUtf8("label_45"))
        self.horizontalLayout_47.addWidget(self.label_45)
        self.exited_soon_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exited_soon_display_2.setFont(font)
        self.exited_soon_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.exited_soon_display_2.setText(_fromUtf8(""))
        self.exited_soon_display_2.setObjectName(_fromUtf8("exited_soon_display_2"))
        self.horizontalLayout_47.addWidget(self.exited_soon_display_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_47)
        spacerItem50 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem50)
        self.horizontalLayout_61 = QtGui.QHBoxLayout()
        self.horizontalLayout_61.setObjectName(_fromUtf8("horizontalLayout_61"))
        self.label_46 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_46.setFont(font)
        self.label_46.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_46.setObjectName(_fromUtf8("label_46"))
        self.horizontalLayout_61.addWidget(self.label_46)
        self.exited_late_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.exited_late_display_2.setFont(font)
        self.exited_late_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.exited_late_display_2.setText(_fromUtf8(""))
        self.exited_late_display_2.setObjectName(_fromUtf8("exited_late_display_2"))
        self.horizontalLayout_61.addWidget(self.exited_late_display_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_61)
        spacerItem51 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem51)
        self.horizontalLayout_62 = QtGui.QHBoxLayout()
        self.horizontalLayout_62.setObjectName(_fromUtf8("horizontalLayout_62"))
        self.label_47 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_47.setFont(font)
        self.label_47.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_47.setObjectName(_fromUtf8("label_47"))
        self.horizontalLayout_62.addWidget(self.label_47)
        self.unplanned_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.unplanned_display_2.setFont(font)
        self.unplanned_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.unplanned_display_2.setText(_fromUtf8(""))
        self.unplanned_display_2.setObjectName(_fromUtf8("unplanned_display_2"))
        self.horizontalLayout_62.addWidget(self.unplanned_display_2)
        self.verticalLayout_17.addLayout(self.horizontalLayout_62)
        self.horizontalLayout_29.addLayout(self.verticalLayout_17)
        spacerItem52 = QtGui.QSpacerItem(98, 20, QtGui.QSizePolicy.Expanding, QtGui.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem52)
        self.verticalLayout_18 = QtGui.QVBoxLayout()
        self.verticalLayout_18.setObjectName(_fromUtf8("verticalLayout_18"))
        self.horizontalLayout_63 = QtGui.QHBoxLayout()
        self.horizontalLayout_63.setObjectName(_fromUtf8("horizontalLayout_63"))
        self.label_48 = QtGui.QLabel(self.layoutWidget_3)
        self.label_48.setMaximumSize(QtCore.QSize(215, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_48.setFont(font)
        self.label_48.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_48.setObjectName(_fromUtf8("label_48"))
        self.horizontalLayout_63.addWidget(self.label_48)
        self.stop_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.stop_display_2.setFont(font)
        self.stop_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);\n"
""))
        self.stop_display_2.setText(_fromUtf8(""))
        self.stop_display_2.setObjectName(_fromUtf8("stop_display_2"))
        self.horizontalLayout_63.addWidget(self.stop_display_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_63)
        spacerItem53 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem53)
        self.horizontalLayout_64 = QtGui.QHBoxLayout()
        self.horizontalLayout_64.setObjectName(_fromUtf8("horizontalLayout_64"))
        self.label_49 = QtGui.QLabel(self.layoutWidget_3)
        self.label_49.setMinimumSize(QtCore.QSize(276, 40))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_49.setFont(font)
        self.label_49.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_49.setObjectName(_fromUtf8("label_49"))
        self.horizontalLayout_64.addWidget(self.label_49)
        self.too_large_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.too_large_display_2.setFont(font)
        self.too_large_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.too_large_display_2.setText(_fromUtf8(""))
        self.too_large_display_2.setObjectName(_fromUtf8("too_large_display_2"))
        self.horizontalLayout_64.addWidget(self.too_large_display_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_64)
        spacerItem54 = QtGui.QSpacerItem(20, 18, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_18.addItem(spacerItem54)
        self.horizontalLayout_65 = QtGui.QHBoxLayout()
        self.horizontalLayout_65.setObjectName(_fromUtf8("horizontalLayout_65"))
        self.label_50 = QtGui.QLabel(self.layoutWidget_3)
        self.label_50.setMinimumSize(QtCore.QSize(150, 34))
        self.label_50.setMaximumSize(QtCore.QSize(126, 34))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_50.setFont(font)
        self.label_50.setStyleSheet(_fromUtf8("color: rgb(255, 255, 255);"))
        self.label_50.setObjectName(_fromUtf8("label_50"))
        self.horizontalLayout_65.addWidget(self.label_50)
        self.hesitated_display_2 = QtGui.QLabel(self.layoutWidget_3)
        font = QtGui.QFont()
        font.setPointSize(10)
        self.hesitated_display_2.setFont(font)
        self.hesitated_display_2.setStyleSheet(_fromUtf8("color: rgb(85, 255, 255);"))
        self.hesitated_display_2.setText(_fromUtf8(""))
        self.hesitated_display_2.setObjectName(_fromUtf8("hesitated_display_2"))
        self.horizontalLayout_65.addWidget(self.hesitated_display_2)
        self.verticalLayout_18.addLayout(self.horizontalLayout_65)
        self.horizontalLayout_29.addLayout(self.verticalLayout_18)
        self.verticalLayout_15.addLayout(self.horizontalLayout_29)
        spacerItem55 = QtGui.QSpacerItem(20, 28, QtGui.QSizePolicy.Minimum, QtGui.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem55)
        self.tabWidget.addTab(self.tab_2, _fromUtf8(""))
        self.gridLayout.addWidget(self.tabWidget, 1, 0, 1, 1)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtGui.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 2558, 47))
        self.menubar.setObjectName(_fromUtf8("menubar"))
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtGui.QStatusBar(MainWindow)
        self.statusbar.setObjectName(_fromUtf8("statusbar"))
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow", None))
        self.label.setText(_translate("MainWindow", "Trader Dashboard", None))
        self.label_8.setText(_translate("MainWindow", "Trades This Year", None))
        self.label_9.setText(_translate("MainWindow", "Trades This Month", None))
        self.label_10.setText(_translate("MainWindow", "Trades Today", None))
        self.label_5.setText(_translate("MainWindow", "Calculations", None))
        self.label_6.setText(_translate("MainWindow", "Risk:Reward Ratio", None))
        self.label_7.setText(_translate("MainWindow", "Entry Price:", None))
        self.label_11.setText(_translate("MainWindow", "Target Price:", None))
        self.label_12.setText(_translate("MainWindow", "Stop Loss:", None))
        self.rr_btn.setText(_translate("MainWindow", "Calculate RR", None))
        self.label_15.setText(_translate("MainWindow", "Before Value:", None))
        self.label_16.setText(_translate("MainWindow", "Current Value:", None))
        self.percent_move_btn.setText(_translate("MainWindow", "Calculate Percent Move", None))
        self.label_14.setText(_translate("MainWindow", "Move Percentage", None))
        self.label_23.setText(_translate("MainWindow", "Add Trade", None))
        self.year_switch_btn.setText(_translate("MainWindow", "<", None))
        self.month_switch_btn.setText(_translate("MainWindow", ">", None))
        self.label_18.setText(_translate("MainWindow", "Trading Issues", None))
        self.label_25.setText(_translate("MainWindow", "Trade Outcome:", None))
        self.trade_outcome_box.setItemText(0, _translate("MainWindow", "Win", None))
        self.trade_outcome_box.setItemText(1, _translate("MainWindow", "Loss", None))
        self.label_27.setText(_translate("MainWindow", "If issue occurred, select:", None))
        self.reason_box.setItemText(0, _translate("MainWindow", "None", None))
        self.reason_box.setItemText(1, _translate("MainWindow", "Poor risk/reward", None))
        self.reason_box.setItemText(2, _translate("MainWindow", "Entered too soon", None))
        self.reason_box.setItemText(3, _translate("MainWindow", "Entered too late", None))
        self.reason_box.setItemText(4, _translate("MainWindow", "Exited too soon", None))
        self.reason_box.setItemText(5, _translate("MainWindow", "Exited too late", None))
        self.reason_box.setItemText(6, _translate("MainWindow", "Unplanned", None))
        self.reason_box.setItemText(7, _translate("MainWindow", "Bad stop loss", None))
        self.reason_box.setItemText(8, _translate("MainWindow", "Position too large", None))
        self.reason_box.setItemText(9, _translate("MainWindow", "Hesitated", None))
        self.add_trade_btn.setText(_translate("MainWindow", "Add Trade", None))
        self.label_33.setText(_translate("MainWindow", "Poor Risk/Reward:", None))
        self.label_35.setText(_translate("MainWindow", "Entered Too Soon:", None))
        self.label_37.setText(_translate("MainWindow", "Entered Too Late:", None))
        self.label_39.setText(_translate("MainWindow", "Exited Too Soon:", None))
        self.label_40.setText(_translate("MainWindow", "Exited Too Late:", None))
        self.label_41.setText(_translate("MainWindow", "Unplanned Trade:", None))
        self.label_42.setText(_translate("MainWindow", "Bad Stop Loss:", None))
        self.label_43.setText(_translate("MainWindow", "Position Too Large:", None))
        self.label_44.setText(_translate("MainWindow", "Hesitated:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab), _translate("MainWindow", "Main", None))
        self.label_24.setText(_translate("MainWindow", "Search", None))
        self.label_2.setText(_translate("MainWindow", "Month:", None))
        self.past_month_menu.setItemText(0, _translate("MainWindow", "None", None))
        self.past_month_menu.setItemText(1, _translate("MainWindow", "01", None))
        self.past_month_menu.setItemText(2, _translate("MainWindow", "02", None))
        self.past_month_menu.setItemText(3, _translate("MainWindow", "03", None))
        self.past_month_menu.setItemText(4, _translate("MainWindow", "04", None))
        self.past_month_menu.setItemText(5, _translate("MainWindow", "05", None))
        self.past_month_menu.setItemText(6, _translate("MainWindow", "06", None))
        self.past_month_menu.setItemText(7, _translate("MainWindow", "07", None))
        self.past_month_menu.setItemText(8, _translate("MainWindow", "08", None))
        self.past_month_menu.setItemText(9, _translate("MainWindow", "09", None))
        self.past_month_menu.setItemText(10, _translate("MainWindow", "10", None))
        self.past_month_menu.setItemText(11, _translate("MainWindow", "11", None))
        self.past_month_menu.setItemText(12, _translate("MainWindow", "12", None))
        self.label_3.setText(_translate("MainWindow", "Year*:", None))
        self.past_stats_search_btn.setText(_translate("MainWindow", "Search", None))
        self.label_4.setText(_translate("MainWindow", "Trading Issues for", None))
        self.label_34.setText(_translate("MainWindow", "Poor Risk/Reward:", None))
        self.label_36.setText(_translate("MainWindow", "Entered Too Soon:", None))
        self.label_38.setText(_translate("MainWindow", "Entered Too Late:", None))
        self.label_45.setText(_translate("MainWindow", "Exited Too Soon:", None))
        self.label_46.setText(_translate("MainWindow", "Exited Too Late:", None))
        self.label_47.setText(_translate("MainWindow", "Unplanned Trade:", None))
        self.label_48.setText(_translate("MainWindow", "Bad Stop Loss:", None))
        self.label_49.setText(_translate("MainWindow", "Position Too Large:", None))
        self.label_50.setText(_translate("MainWindow", "Hesitated:", None))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_2), _translate("MainWindow", "Past Stats", None))

